version: '3'

services:

  flask:
    build:
      context: ../
      dockerfile: etc/flask.Dockerfile
    environment:
      FLASK_APP: app/__init__.py
      FLASK_DEBUG: 1
      LOG_TO_STDOUT: 1
    ports:
      - 5000:5000
    restart: always
    volumes:
      - "../app:/home/flask_app/app"
      - "../data:/home/flask_app/data"
      - "../ml:/home/flask_app/ml"
      - "../models:/home/flask_app/models"

  react:
    build:
      context: ../
      dockerfile: etc/react.Dockerfile
    depends_on:
      - flask
    environment:
      NODE_ENV: development
      REACT_APP_API_BASE: http://localhost:5000
    links:
      - flask
    ports:
      - 3000:3000
    restart: always
    volumes:
      - "../frontend:/home/react_app"
